### PR TITLE
i like sushi.

### PR DESCRIPTION
**Pull request by ghost**
Do you like sushi? @m-okubo2 @kntk 
- [x] maguro
- [x] uni
- [ ] AIEE

### CODE REVIEW

**Comment by githubteacher** [comment]
@tarakaki Me too! :sushi:

**Comment by ghost** [comment]
I love maguro too. :100:

**Comment by mmurasawa** [comment]
- [ ] :sushi: 
- [ ] :sake:

**Comment by ochiba** [comment]
I like salmon

**Comment by githubteacher** [comment]
**EDITED OP** Added blah.

**Pull request merged**
